In [16]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [17]:
data = pd.read_csv('glass.csv')

In [18]:
from sklearn import svm
from sklearn.svm import SVC
X = data.drop('Type',axis = 1)
Y = data['Type']

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=25,random_state=101)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [20]:
linear = SVC(kernel='linear')
linear.fit(x_train, y_train)
y_pred0 = linear.predict(x_test)
print( accuracy_score(y_test, y_pred0))
print(confusion_matrix(y_test, y_pred0))
print(classification_report(y_test, y_pred0))

1.0
[[9 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 5 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 3]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         5
           3       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         3

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25



In [21]:
sigmoid = SVC(kernel='sigmoid')
poly = SVC(kernel='poly')
rbf = SVC(kernel='rbf')

In [22]:
sigmoid.fit(x_train,y_train)
poly.fit(x_train,y_train)
rbf.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [23]:
y_pred1 = sigmoid.predict(x_test)
y_pred2 = poly.predict(x_test)
y_pred3 = rbf.predict(x_test)

In [24]:
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

0.2
[[0 9 0 0 0 0]
 [0 5 0 0 0 0]
 [0 5 0 0 0 0]
 [0 2 0 0 0 0]
 [0 1 0 0 0 0]
 [0 3 0 0 0 0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         9
           2       0.20      1.00      0.33         5
           3       0.00      0.00      0.00         5
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         3

    accuracy                           0.20        25
   macro avg       0.03      0.17      0.06        25
weighted avg       0.04      0.20      0.07        25



In [25]:
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

1.0
[[9 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 5 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 3]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         5
           3       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         3

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25



In [26]:
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

0.92
[[9 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 5 0 0 0]
 [0 0 0 2 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 2]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         9
           2       0.71      1.00      0.83         5
           3       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         2
           6       0.00      0.00      0.00         1
           7       1.00      0.67      0.80         3

    accuracy                           0.92        25
   macro avg       0.79      0.78      0.77        25
weighted avg       0.90      0.92      0.90        25

